
Schema.org is an initiative launched on 2 June 2011 by Bing, Google and Yahoo!Google's blog postBing's blog postYahoo!s blog posts to "create and support a common set of schemas for structured data markup on web pages." On 1 November Yandex (largest search engine in Russia) joined the initiative Techcrunch "Yandex joins Google, Yahoo! and Bing to collaborate on Schema.org"Schema Blog "Yandex now supports schema.org markup". The operators of the world's largest search engines
Much of the vocabulary on schema.org was inspired by earlier formats such as Microformats, FOAF, GoodRelations and OpenCyc.
A canonical mapping from the terms defined in Schema.org to RDF (expressed in RDF Schema) is available. Schema.RDFS.org

== Example ==

The following is an example of how to embed information about a movie and the structure of the information into a website. In order to mark up the data the attribute itemtype along with the url of the schema is used. The attribute itemscope defines the scope of the itemtype. The kind of the current item can be defined by using the attribute itemprop. Within the schema for a movie is a schema for a person.

==References==

== External links ==

* Schema.org
* original discussion group, now moved to W3C
* GetSchema Annotating HTML5 with Schema.org and Microdata. An Example Wiki.
* Free Schema.org Parser 

